// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

let lastFib = 0;
let n = 1;
let fibSum = 0;

while (lastFib <= 4000000) {
  if (lastFib % 2 === 0) {
    fibSum += lastFib;
  }
  lastFib = findFib(n);
  n++;
}

function findFib(n) {
  if (n === 0) {
    return 0;
  } else if (n === 1) {
    return 1;
  } else {
    return findFib(n - 1) + findFib(n - 2);
  }
}
